### ISSUE TITLE
Run Runners in No Graphics mode

### ISSUE THREAD

**Issue by AndreiChenchik** [shapehq/tartelet#100]
### Is your feature request related to a problem?

Yes, the problem is that I can't use Tartelet on my developer machine, due to the fact that VM restart leads to screen appearing in Foreground interrupting my work.

### What solution would you like?

Start VMs with `--no-graphics` flag from tartelet, it will be something like `tart run runner --no-graphics`

### What alternatives have you considered?

I've tried to create separate user (with macos fast user switching) and run tartelet from there, but it seems that while you switched to another user you can't have VMs started, they are waiting until the user will became active, so it's not working.

### Any additional context?

`--no-graphics` mode behave a bit differently, in that mode the shell will be waiting until the process will be finished (vm stopped)

**Comment by kuhnroyal** [comment]
You can try running the latest version 0.10.2 with the separate user. Just a guess but the fix for #98 might help there.

**Comment by AndreiChenchik** [comment]
@kuhnroyal ready to try, but can't see an app in resources. Is there a new app with this version?

**Comment by simonbs** [comment]
> @kuhnroyal ready to try, but can't see an app in resources. Is there a new app with this version?

That's my bad. The binary is now included as an asset in the 0.10.2 release: https://github.com/shapehq/tartelet/releases/tag/0.10.2

**Comment by AndreiChenchik** [comment]
Thank you all guys! I've tried it but it seems to be it's not working.

Interestingly, when I go back to the runner-user I can see how runners loading stuck in the middle. I can see macos loader just at the center, like it was waiting for display link or something.

**Comment by AndreiChenchik** [comment]
I've tried to connect via SSH to tartelet-user and it seems that the issue is not with the tart itself. 

1. I was able to start new node via ssh using `tart run` and was able to connect to it using ssh
2. **I've noticed that it's not that runner is just stuck in the middle of loading**, it's Tartelet is continiously restarting the runner in a loop 
3. I will try to find logs and attach it here

**Comment by AndreiChenchik** [comment]
Well, you were right, it's private key, the app version is 0.10.2 (1)
```text
08:41:53.872 INFO: Start virtual machine named runner-2
08:42:07.633 INFO: The private key is not available
08:42:07.636 INFO: Could not connect to the virtual machine over SSH, so the virtual machine will be shut down.
08:42:07.667 INFO: Virtual machine named runner-2 stopped with message: Failed establishing SSH connection
08:42:08.097 INFO: Start virtual machine named runner-2
08:42:20.998 INFO: The private key is not available
08:42:21.020 INFO: Could not connect to the virtual machine over SSH, so the virtual machine will be shut down.
08:42:21.053 INFO: Virtual machine named runner-2 stopped with message: Failed establishing SSH connection
08:42:21.522 INFO: Start virtual machine named runner-2
08:42:35.087 INFO: The private key is not available
08:42:35.089 INFO: Could not connect to the virtual machine over SSH, so the virtual machine will be shut down.
08:42:35.118 INFO: Virtual machine named runner-2 stopped with message: Failed establishing SSH connection
08:42:35.539 INFO: Start virtual machine named runner-2
08:42:49.405 INFO: The private key is not available
08:42:49.426 INFO: Could not connect to the virtual machine over SSH, so the virtual machine will be shut down.
08:42:49.538 INFO: Virtual machine named runner-2 stopped with message: Failed establishing SSH connection
08:42:49.952 INFO: Start virtual machine named runner-2
08:43:03.517 INFO: The private key is not available
08:43:03.556 INFO: Could not connect to the virtual machine over SSH, so the virtual machine will be shut down.
08:43:03.596 INFO: Virtual machine named runner-2 stopped with message: Failed establishing SSH connection
08:43:04.034 INFO: Start virtual machine named runner-2
08:43:17.770 INFO: The private key is not available
08:43:17.774 INFO: Could not connect to the virtual machine over SSH, so the virtual machine will be shut down.
08:43:17.874 INFO: Virtual machine named runner-2 stopped with message: Failed establishing SSH connection
08:43:18.309 INFO: Start virtual machine named runner-2
```

**Comment by AndreiChenchik** [comment]
I went into the #98 and realized that the items getting that flag on save.
I've reattached the cert file to Tartelet and now it's working like a charm. 

@kuhnroyal @simonbs thank you for your help!

Closing since there is no more issue.

**Comment by kuhnroyal** [comment]
Yes, sorry forgot to mention this :/
