### ISSUE TITLE
Debug mode or logging output

### ISSUE THREAD

**Issue by Flasheh** [shapehq/tartelet#3]
Hi

I am trying out this project for a client and so far it seems very promising, thanks for sharing it with the community.

However I was stuck during the setup for a very long time because I forgot the "install" the GitHub App I created inside our GitHub organisation. It was a very small and stupid error but I could not find any kind of debug mode or logging which could have easily told me the authorization with GitHub was failing.

Is there a way that could have helped me troubleshoot Tartelet? I'm not too familiar with macOS so I could have missed something. Or is this something that is still on the roadmap for the app?

Thanks!

**Comment by simonbs** [comment]
Thanks for opening the issue. Tartelet is indeed missing some error reporting and/or logging. I'm hoping to add that soon-ish.

**Comment by simonbs** [comment]
I have introduced logging in #16, #17, #19, #20, and #21. I will expand on this over time, especially when we catch new issues that could have been easier to debug with logging.

With logging added I consider this issue solved and will close it but please don't hesitate to reopen the issue if the problem remains.
