### ISSUE TITLE
Unexpected termination status: 64

### ISSUE THREAD

**Issue by stmitt** [shapehq/tartelet#38]
Hi, 
I'm experiencing issues when using the latest versions of Tartlet (0.4) and Tart (1.7.0) together. Specifically, when I click "Start," the virtual machines don't start. In the logs, I see the following information:

```
2023-06-29T13:07:58Z [VirtualMachineFleetLive] [Info] Start virtual machine named macos-ventura-xcode:14.3.1-1
2023-06-29T13:07:58Z [EphemeralTartVirtualMachine] [Info] Clone Tart image named macos-ventura-xcode:14.3.1 to macos-ventura-xcode:14.3.1-1...
2023-06-29T13:07:58Z [EphemeralTartVirtualMachine] [Info] Run Tart image named macos-ventura-xcode:14.3.1-1...
2023-06-29T13:07:58Z [VirtualMachineFleetLive] [Info] Virtual machine named macos-ventura-xcode:14.3.1-1 stopped with message: Unexpected termination status: 64
```

However, if I manually start the virtual machine through the "Edit Virtual Machine" option, it starts as expected.

**Comment by stmitt** [comment]
I found the following logs in the systemlogs:
```
error	22:25:07.137901+0200	Tartelet	Failed making ephemeral virtual machine as resources could not be created: cancelled
error	22:25:07.138052+0200	Tartelet	Could not create virtual machine named ventura-xcode:14.3.1-1: cancelled
```

**Comment by simonbs** [comment]
@stmitt Are you seeing this issue with Tart 1.7.0 specifically? I just tested with the newest version of Tart, as of writing this that is 1.9.1, and that seems to work fine.

**Comment by stmitt** [comment]
@simonbs yes i'm still seeing this issue with Tart 1.9.1. Specifically when using this image: https://github.com/cirruslabs/macos-image-templates/pkgs/container/macos-ventura-xcode/101275224?tag=14.3.1

**Comment by simonbs** [comment]
@stmitt Do you know if the issue occurs when using other images too?

**Comment by stmitt** [comment]
@simonbs I was able to create a image following the tartelet instruction which works. Do the cirruslabs images work with your setup?

**Comment by simonbs** [comment]
@stmitt I have not tested with CirrusLabs' images. I can't see why they shouldn't work though.

**Comment by stmitt** [comment]
I found out what the issue in my setup was:
I named the cloned image "macos-ventura-xcode_14.3.1". Since the colon[ is used as a separator](https://github.com/cirruslabs/tart/blob/feb733a7c09dcdd5e305603120948cddbd1573b7/Sources/tart/Commands/Run.swift#L596) in the tart run command, the command is failing. Therefore, I propose to replace all colons in the directory with underscores. I created a PR that does that: https://github.com/shapehq/tartelet/pull/43

**Comment by simonbs** [comment]
Closing this as #43 is merged.

Thanks for looking into the issue and providing a fix! 🙏
