### ISSUE TITLE
Sometimes the second virtual machine is not started

### ISSUE THREAD

**Issue by simonbs** [shapehq/tartelet#4]
There's an issue where sometimes Tartelet will go from maintaining two virtual machines to only one, even when configured to maintain two.

**Workaround**:
1. Stop Tartelet.
2. Start Tartelet.

This will address the issue for a while but it may eventually happen again.

I'll find some time to look into this issue. I think it can be resolved by vastly simplifying the way virtual machines are maintained.

**Comment by simonbs** [comment]
This seems to be fixed by #7. I'm not entirely sure of the root cause behind this issue but the logic was overly complex and rewriting it to be much simpler seems to have addressed the issue. I will reopen the issue if that turns out not to be the case anyway.

**Comment by jfro** [comment]
relaunching tartlet resolved... basically I found out neither were running after a power outage & mini booted up after outage and tartlet was open, claimed it was running the VMs but saw neither of the UIs (or their presence in github runners UI)
