### ISSUE TITLE
Best practice for setting environment variables?

### ISSUE THREAD

**Issue by xavierLowmiller** [shapehq/tartelet#40]
I think I have a plan, but want to make sure:

Are there any best practices for setting environment variables on runner VM instances?

Background: I'm trying to set up our runners for Android builds, and need to set `ANDROID_HOME`, which ideally should always be available.

I'm looking into using `launchctl setenv` (as described [here](https://stackoverflow.com/a/3756686)), but I'm wondering if there is an "official" tartelet way of doing this?

**Comment by simonbs** [comment]
Tartelet has no functionality for working with environment variables specifically. You could add a pre-run script that configures the environment variables you need. You'll find a guide on setting that up [in the wiki](https://github.com/shapehq/tartelet/wiki/Adding-Pre--and-Post-Run-Scripts).

Personally, I'd define the environment variable within your workflows so you ensure your workflows remain as portable as possible. You can do that using the `env` key in a workflow as shown below.

```yml
env:
  ANDROID_HOME: /Users/runner/your/path
```

**Comment by xavierLowmiller** [comment]
Excellent, thank you for the link Simon!
