### ISSUE TITLE
Unable to start VMs

### ISSUE THREAD

**Issue by thermogl** [shapehq/tartelet#55]
I'm seeing the following in the console:
```
Could not create virtual machine named runner-2: The GitHub app has not been installed. Please install it from the developer settings.
```
I have installed the app in the GitHub org settings, though, so not sure what else to try?
![Screenshot 2023-10-16 at 15 04 33](https://github.com/shapehq/tartelet/assets/215950/43424413-231c-4638-bf21-c6f9677bff20)

**Comment by antonnyman** [comment]
@thermogl Getting the same issue, how did you solve it?

**Comment by thermogl** [comment]
For me, the org name was case sensitive. When I fixed that it started working

**Comment by antonnyman** [comment]
Thanks! This worked!
I was using `myorg` insted of `MyOrg`. Changing it to `MyOrg` worked.
