### ISSUE TITLE
My Shared Files not showing

### ISSUE THREAD

**Issue by oschusler** [shapehq/tartelet#58]
A few months ago, I set up a Mac mini M2 with Tartelet. For this, I followed the entire wiki (setting up the host, installing Tartelet and configuring Tartelet). Everything worked perfect.

Due to circumstances, I had to install the machine again. However, when I now follow the same tutorial, I don't see the "My Shared Files" in finder when editing the VM. I even downgraded the version of Tartelet to 0.6.0.

I also tried to export the logs, but hitting that button doesn't seem to do anything. Does anyone have any idea what might be the issue?

**Comment by fkorotkov** [comment]
Looks like a regression in macOS 14.2. Please try to install 14.3 Beta. See https://github.com/cirruslabs/tart/issues/687 for details.

**Comment by oschusler** [comment]
Thanks for the very swift response!
