### ISSUE TITLE
Question: Should runner account be standard or admin?

### ISSUE THREAD

**Issue by hisaac** [shapehq/tartelet#62]
I had a question about a recommendation made in Tartelet's Wiki.

In the Setting Up a Host Machine page, it advises:

> Create an account named "runner" through the Users & Groups pane in System Settings. It is important that this is a standard account, that is, it should not be an administrator. We will use this account to run the Tartelet application.

It later goes on to outline how to grant the account `sudo` privileges, which sort of makes it not exactly a standard account anyway.

Could you clarify why it's important that this is a standard account and not an admin? I'm sure there's a good reason, so I'd just like to understand it better.

**Comment by simonbs** [comment]
Sorry for the late reply and thank you for your patience.

It's a great question and you have a good point. I suppose it isn't important that this is a standard account. When I wrote this, I deemed it best practice to make the runner a standard account as it doesn't need to be an administrator, but it does need to be in the sudoers file. It's not important, though.

**Comment by simonbs** [comment]
I've rephrased the guide to say

> This can be a standard account; that is, it does not need to be an administrator account.

and as such, I consider this issue closed.

Please don't hesitate to open it again if you have any follow up questions 😊

**Comment by hisaac** [comment]
Thanks @simonbs 🙏
