### ISSUE TITLE
Failed making ephemeral virtual machine, missing permissions

### ISSUE THREAD

**Issue by antonnyman** [shapehq/tartelet#63]
Hi, I'm getting this error when starting the VM's.

```
Failed making ephemeral virtual machine as resources could not be created: “.Trashes” couldn’t be copied because you don’t have permission to access “runner-1”.
```

Unsure what needs permission to perform the copy action?

### System
Mac mini, M1 2020
macOS Sonoma 14.3.1

**Comment by antonnyman** [comment]
I deleted `Application Support/dk.shape.Tartelet` and added the files manually. Now the VM starts (until I close the desktop app). However it seems like the VM can't find `/Volumes/My Shared Files/Resources` and it will start boot looping.

**Comment by antonnyman** [comment]
I got it to work by manually creating a `Resources` folder in `Virtual Machine Resources`, then while VM booted I copied the generated code to `runner-1/Resources/start.command` along with the generated files.

To me it seems like there are two issues, the script expects a `Resources` folder but there is none, and the macOS app doesn't have permission to copy/create certain folders.

Any ideas on where to start on a fix to this?

**Comment by antonnyman** [comment]
I got it to work by manually creating a `Resources` folder in `Virtual Machine Resources`, then while VM booted I copied the generated code to `runner-1/Resources/start.command` along with the generated files.

To me it seems like there are two issues, the script expects a `Resources` folder but there is none, and the macOS app doesn't have permission to copy/create certain folders.

Any ideas on where to start on a fix to this?

**Comment by antonnyman** [comment]
I managed to solve the first issue that resources couldn't be copied.
This error went away after I emptied the bin 🤦 

Still having an issue that files in `runner-1` are copied to the root directory and not `runner-1/Resources`.
Closing this issue and opening a new one.

**Comment by annuh** [comment]
@antonnyman I'm having the same issues! Did you find a solution for the other issue?

<img width="585" alt="image" src="https://github.com/shapehq/tartelet/assets/2487949/9a02d31a-66e7-4203-9496-24f822a0dea9">
