### ISSUE TITLE
Sporadic crashes

### ISSUE THREAD

**Issue by tonyarnold** [shapehq/tartelet#93]
### What happened?

Tartelet is crashing for me on my CI boxes.

### What are the steps to reproduce?

There's no way to reliably reproduce the issue, but it happens at least once a day.

Here is the crash report: 

[Tartelet-2024-09-04-181504.ips.zip](https://github.com/user-attachments/files/16929474/Tartelet-2024-09-04-181504.ips.zip)

### What is the expected behavior?

Tartlet doesn't crash.

**Comment by tonyarnold** [comment]
@simonbs do you keep copies of the dSYMs so that I might be able to help fix this?

**Comment by kuhnroyal** [comment]
I am getting the same crash trace.
Both are Tartelet 0.9.0 on MacOS 14.6 & 15.1

[Tartelet-2024-11-08-013250.ips.zip](https://github.com/user-attachments/files/17676651/Tartelet-2024-11-08-013250.ips.zip)

Would be great if this could be investigated.

**Comment by kuhnroyal** [comment]
Seeing that there is a 0.10.0 in the repo but not available via brew.

**Comment by simonbs** [comment]
I don't have a lot of time to investigate this, unfortunately, but if anyone does, I'd be happy to review a PR with a fix 🤗

**Comment by kuhnroyal** [comment]
Do you have the Symbols from the 0.9.0 build?

**Comment by kuhnroyal** [comment]
Actually the 0.10.0 build (the `MARKETING_VERSION` was not bumped before the release).

**Comment by simonbs** [comment]
I do not seem to have the symbols anymore, unfortunately. If you'd like to look into this, you may need to create and sign a new build.

**Comment by kuhnroyal** [comment]
Hmm this doesn't seem to work, too many things related to signing in order to access the Keychain and Github Key.
Would be great if you can just create a new version with symbols.

**Comment by kuhnroyal** [comment]
So it seems there is a bad file descriptor error when running `tart ip NAME` during VM startup.

**Comment by kuhnroyal** [comment]
I think this is the culprit https://github.com/swiftlang/swift/issues/57827
We are just running out of file descriptors for the `Pipe`s.
