### ISSUE TITLE
Configuring Github App for Organization

### ISSUE THREAD

**Issue by ryanhanks-bestow** [shapehq/tartelet#95]
### Your Question

I followed https://github.com/shapehq/tartelet/wiki/Configuring-Tartelet to create and configure the Github App for my organization. I was [having trouble getting the runner to run locally](https://github.com/shapehq/tartelet/issues/94), and in the midst of fuddling around trying to fix it, I came stumbled upon this `Install App` menu option on https://github.com/organizations/%7BYOUR_ORGANIZATION_NAME%7D/settings/apps:

<img width="314" alt="Screenshot 2024-09-28 at 11 00 40 PM" src="https://github.com/user-attachments/assets/3e13b868-919b-48f8-8b88-00c34b68be25">

It seemed necessary, so I did it for my org.

Was this a required step? I don't see it mentioned in the guide to configuring the github App for an organization.

**Comment by patriknyblad** [comment]
I have just been through the same journey again, although this time we refactored our github apps a bit to create a specific one just for the runners registered using tartelet. 

*I can confirm that I also had to "install" the app into the org after creating the app, you did the correct thing* ✅

(Don't remember if it was like that last time I set it up as that was a couple of years ago now.)

**Comment by simonbs** [comment]
It is indeed necessary to install the GitHub app on the organization. I've updated the guide to reflect this requirement. Thanks for pointing out the missing step.
